timezone: America/Sao_Paulo
title: Rodrigo Muniz
#host: muniz.nu
# baseurl: /muniz.nu
permalink: blog/:title
sass:
    style: :compressed
githuburl: https://muniz.nu

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
