timezone: America/Sao_Paulo
title: Rodrigo Muniz
#host: muniz.nu
# baseurl: /muniz.nu
permalink: blog/:title
githuburl: https://muniz.nu

collections:
  portfolio:
    output: true
    permalink: /design/:path/
